sudo: false
language: php
dist: trusty
php:
  - '7.0'
before_script:
  - pecl -q install mongodb && echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install -o